---
services: docker

env:
  # Test package install on all supported OSes.
  - distro: centos7
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE
  - distro: fedora24
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE
  - distro: debian8
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE
  - distro: ubuntu1604
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE
  - distro: ubuntu1404
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure Moodle is running
  - 'docker exec --tty ${container_id} env TERM=xterm curl http://moodle.test/ |  grep "MTS"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
