---
services: docker

env:
  # Test package install on all supported OSes (for now only Debian/Ubuntu).
  # There are several issues with CentOS7 (postgres version < 9.3) and issue
  # with git playbook on fedora 24
  - distro: debian9
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE
  - distro: centos7
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE
  - distro: ubuntu1604
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE
  - distro: ubuntu1804
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE
  - distro: ubuntu1404
    playbook: test.yml
    moodle_version: MOODLE_34_STABLE

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false

  # Download test shim.
  #- wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/geerlingguy/73ef1e5ee45d8694570f334be385e181/raw/
  #- chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Make sure Moodle is running
  - 'docker exec --tty ${container_id} env TERM=xterm curl http://moodle.test/ |  grep "MTS"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
