---

- import_tasks: setupdirs.yml
- import_tasks: fetchsources.yml

- name: Moodle - Create config template and trigger install
  template:
    src: config.php.j2
    dest: "{{ moodle_src_path }}/config.php"
    mode: 0644
  notify: intiate moodle configuration
  when: moodle_run_config|bool and moodle_site_source_stat is defined and not moodle_site_source_stat.stat.exists
