---
# Creates the relevant directories to install moodle:
# - a source directory
# - a data directory where we will have all site data
- name: Moodle- Check before if installation directory exists
  stat:
    path: "{{ moodle_src_path }}/config.php"
  register: moodle_site_source_stat

- name: Moodle- Create installation directory if it does not exist
  file:
    dest: "{{ moodle_src_path }}"
    state: directory
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
  become: yes


- name: Moodle- Create shared data directory if it does not exist
  file:
    dest: "{{ moodle_sitedata.shared_data_folder }}"
    state: directory
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    mode: "u=rwx,g=rwx,o=r"
  become: yes

- name: Moodle- Create local data directory if it does not exist
  file:
    dest: "{{ moodle_sitedata.local_data_folder }}"
    state: directory
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    mode: "u=rwx,g=rwx,o=r"
  become: yes

- name: Moodle- Create local cache directory if it does not exist
  file:
    dest: "{{ moodle_sitedata.local_data_folder }}/{{ moodle_sitedata.cache_dir_name }}"
    state: directory
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    mode: "u=rwx,g=rwx,o=r"
  become: yes

- name: Moodle- Create shared directories if it does not exist
  file:
    dest: "{{ moodle_sitedata.shared_data_folder }}/{{ moodle_sitedata.data_dir_name }}"
    state: directory
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    mode: "u=rwx,g=rwx,o=r"
  become: yes
  when: shared_drive_subfolder_create|bool

- name: Moodle- Create shared temp directory if it does not exist
  file:
    dest: "{{ moodle_sitedata.shared_data_folder }}/{{ moodle_sitedata.temp_dir_name }}"
    state: directory
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    mode: "u=rwx,g=rwx,o=r"
  become: yes
  when: shared_drive_subfolder_create|bool

- name: Moodle- Create shared cache directory if it does not exist
  file:
    dest: "{{ moodle_sitedata.shared_data_folder }}/{{ moodle_sitedata.cache_dir_name }}"
    state: directory
    owner: "{{ moodle_webserver_user }}"
    group: "{{ moodle_webserver_group }}"
    mode: "u=rwx,g=rwx,o=r"
  become: yes
  when: shared_drive_subfolder_create|bool