---

- name: moodle installer
  listen: install moodle
  command: >
    php admin/cli/install_database.php --adminuser={{ moodle_site_admin.username }} --adminpass={{ moodle_site_admin.password }}
    --adminemail={{ moodle_site_admin.email }} --agree-license --fullname={{ moodle_site_fullname }} --shortname={{ moodle_site_shortname }}
  args:
    chdir: "{{ moodle_src_path }}"

- name: moodle upgrader
  listen: upgrade moodle
  command: >
    php admin/cli/upgrade.php --non-interactive
  args:
    chdir: "{{ moodle_src_path }}"

